In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import mean_squared_error 

In [2]:
dataset =pd.read_csv('Mini_project.csv')

In [3]:
dataset

expierence   location qualification  salary            sector  \
0             0  Hyderabad        B.Tech  100000       Telecom ISP   
1             0  Hyderabad        B.Tech  100000       Telecom ISP   
2             0  Hyderabad        B.Tech  200000       Telecom ISP   
3             0  Hyderabad        B.Tech  200000       Telecom ISP   
4             0  Hyderabad        B.Tech  100000       Telecom ISP   
..          ...        ...           ...     ...               ...   
104           2     Mumbai           BHM  200000  Hotel Management   
105           2     Mumbai           BHM  200000  Hotel Management   
106           0   Banglore           BHM  200000  Hotel Management   
107           2     Mumbai           BHM  200000  Hotel Management   
108           1  Hyderabad           BHM  200000  Hotel Management   

                              job  
0                 Field Engineers  
1                    UI Developer  
2                Trainee Engineer  
3                      SEO intern  
4                 Field Engineers  
..                            ...  
104  Assistant Restaurant Manager  
105            Restaurant Manager  
106        Social Media Executive  
107                          Chef  
108             South Indian Chef  

[109 rows x 6 columns]

In [7]:
X=dataset.iloc[:, [0,1,2,3,4]].values
Y=dataset.iloc[:, 5].values

In [8]:
X

array([[0, 'Hyderabad', 'B.Tech', 100000, 'Telecom ISP'],
       [0, 'Hyderabad', 'B.Tech', 100000, 'Telecom ISP'],
       [0, 'Hyderabad', 'B.Tech', 200000, 'Telecom ISP'],
       [0, 'Hyderabad', 'B.Tech', 200000, 'Telecom ISP'],
       [0, 'Hyderabad', 'B.Tech', 100000, 'Telecom ISP'],
       [0, 'Hyderabad', 'B.Tech', 100000, 'Telecom ISP'],
       [0, 'Hyderabad', 'B.Tech', 200000, 'Telecom ISP'],
       [0, 'Hyderabad', 'B.Tech', 200000, 'Telecom ISP'],
       [0, 'Hyderabad', 'B.Tech', 400000, 'Telecom ISP'],
       [0, 'Hyderabad', 'B.Tech', 400000, 'Telecom ISP'],
       [0, 'Banglore', 'B.Tech', 175000, 'IT-Software'],
       [0, 'Rajkot', 'B.Tech', 180000, 'IT-Software'],
       [0, 'Pune', 'B.Tech', 125000, 'IT-Software'],
       [1, 'Nagpur', 'B.Tech', 60000, 'IT-Software'],
       [1, 'Gurgoan', 'B.Tech', 275000, 'IT-Software'],
       [1, 'Surat', 'B.Tech', 100000, 'IT-Software'],
       [1, 'Agra', 'B.Tech', 275000, 'IT-Software'],
       [1, 'Mohali', 'B.Tech', 175000,

In [6]:
Y

array(['Field Engineers', 'UI Developer', 'Trainee Engineer',
       'SEO intern', 'Field Engineers', 'UI Developer',
       'Trainee Engineer', 'SEO intern', 'Digital Markating consultant',
       'Digital Markating consultant', 'Web Designer',
       'Software Engineer', 'Desktop Engineer', 'Php Developer',
       'Data operation Engineer', 'Andriod Developer',
       'Mobile App Developer', 'Mobile App Developer',
       'Telecommunications Engineer', 'Software Engineer',
       'Business Development ', 'Business Development ',
       'Business Development ', 'Sales Executive', 'Sales Coordinator',
       'Business Development Executive', 'Business Development Executive',
       'Online Sales Executive', 'Sales Associate', 'Marketing Executive',
       'Computer Operator', 'Business Development Executive',
       'Sales Support', 'Management Trainee', 'Assistant Credit Manager',
       'Operation Executive', 'Client Service Executive', 'Jr Accountant',
       'Sr Sales Executive', '

In [9]:
labelencoder_X=LabelEncoder()
# X[:, 0]=labelencoder_X.fit_transform(X[:, 0])
# X[:, 1]=labelencoder_X.fit_transform(X[:, 1])
onehotencoder_X=OneHotEncoder()
X=onehotencoder_X.fit_transform(X).toarray()
labelencoder_Y=LabelEncoder()
Y=labelencoder_Y.fit_transform(Y)

In [10]:
X_train,X_test,y_train,Y_test=train_test_split(X, Y, test_size=0.2,random_state=0)

In [16]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
X_train

array([[0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [12]:
X_test

array([[0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.]])

In [14]:
y_train

array([21, 29, 52, 65, 59, 15, 28, 79, 14, 75, 30, 29, 19, 32, 55, 77, 58,
       35, 57, 39,  7, 80, 27, 40, 43, 41,  1, 54,  0, 74, 80, 44, 52, 44,
       41,  2, 66, 35, 17, 72, 58, 56, 68, 21, 29, 49, 31, 51, 69, 16, 33,
       60, 72, 53, 44, 71, 25, 70, 10, 20, 18, 13, 62, 21, 50,  8, 76, 46,
       29, 22, 58,  5, 36, 29, 78, 39, 11, 26, 20, 38, 37, 48, 64, 47, 58,
       24, 42])

In [15]:
Y_test

array([38, 81, 60, 79, 67, 63, 73, 65, 54, 23,  3, 20,  4, 45, 12, 44, 61,
        9, 34, 44,  6, 37])

In [17]:
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [18]:
y_pred = classifier.predict(X_test)

In [19]:
y_pred

array([16, 72, 39, 65, 69, 18, 52, 65, 72, 11, 27, 66, 72, 52,  8, 43, 72,
        8, 30, 44, 25, 37])

In [21]:
print(mean_squared_error(Y_test,y_pred),max(Y) )
print(y_pred,Y_test)

546.4090909090909 81
[16 72 39 65 69 18 52 65 72 11 27 66 72 52  8 43 72  8 30 44 25 37] [38 81 60 79 67 63 73 65 54 23  3 20  4 45 12 44 61  9 34 44  6 37]


In [20]:
import joblib

In [22]:
joblib.dump(classifier,'RFModelforMPG.pkl')
joblib.dump(onehotencoder_X,'RFModelforMPG1.pkl')
joblib.dump(labelencoder_Y,'RFModelforMPG2.pkl')

['RFModelforMPG2.pkl']

In [23]:
modelReload=joblib.load('RFModelforMPG.pkl')

In [ ]:
modelReload.predict(X_test)

In [ ]:
temp={}
temp['sector']='Sales'
temp['location']='Mumbai'
temp['salary']=200000
temp['qualification']='MBA'
temp['expierence']=0

In [ ]:
testDtaa=pd.DataFrame({'x':temp}).transpose()

In [ ]:
testDtaa

In [ ]:
testDtaa=onehotencoder_X.transform(testDtaa).toarray()

In [ ]:
testDtaa

In [ ]:
modelReload.predict(testDtaa)[0]

In [ ]:
print(Y)

In [ ]:
res=labelencoder_Y.inverse_transform([modelReload.predict(testDtaa)[0]])
print(res)